### ISSUE TITLE
Only show expected metadata files

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-metadata-viz#11]
When a modality is selected, it would be great if the summary of metadata files would only show the files that are expected for that modality - or shade out the ones that aren't expected. E.g. rig/session are expected for physiology and behavior modalities, but not for SPIM. And SPIM/Confocla should have instrument/acquisition. I don't know if this is reasonable, but it would help avoid situations where we fixate on "fixing" missing files that we don't expect to have.

**Comment by dbirman** [comment]
Blocked by https://github.com/AllenNeuralDynamics/aind-data-schema-models/issues/76
