### ISSUE TITLE
Prod deployment

### ISSUE THREAD

**Issue by dbirman** [AllenNeuralDynamics/aind-metadata-viz#26]
**Is your feature request related to a problem? Please describe.**
Deploy the app to prod

**Describe the solution you'd like**

- [ ] Deploy to prod
- [ ] ENV key pointed to prod
- [ ] Domain name: metadata-portal.allenneuraldynamics.org
- [ ] Automatic refresh of AWS triggered by gh workflows

**Comment by jtyoung84** [comment]
It doesn't cost too much to keep it running in dev and prod.

**Comment by dbirman** [comment]
> It doesn't cost too much to keep it running in dev and prod.

Okay I re-wrote where we just leave dev running
